### PR TITLE
Filter combining

### PR DESCRIPTION
**Pull request by viktornoskire**
## Big rework of the filters to work together.
**This work was made by both Viktor and Rikard with LiveShare**

- Created new files: "allFilter.js", "filterTest.md".
- Put all filter in their own folder.
- All old filter calls are removed and replaced by a function which in turn calls all filters functions.
- Reworked code in "filterByLabel.js", "textFilter.js", "type_filter.js" and a small amount in "rating_filter.js"
- "allFilter.js" now works as a hub for the filter functions data. 
- Error message when no challenges are shown, are now in the "applyFilters" function so all filter have access to the same message.
- The "applyFilters" is now responsible of displaying challenges instead of each individual filter function.
- We also made a new folder with the test for the filters. Also made by Rikard and Viktor.

### Image preview: 
_All filters have been selected and none of them push each other out_
allFilters

### CODE REVIEW

**Comment by nilsishome** [comment]
Looks fantastic and ready to be merged!

**Comment by Hungryhippoafk** [comment]
Looks good! Excellent work! 👍

**Comment by Kalu32k** [comment]
Looks good, works as intended.

**Comment by Nishune** [comment]
I think it looks good, but im biased since i also wrote this code :D

**Pull request merged**
