### PR TITLE
Filter challenges by rating

### PR DESCRIPTION
**Pull request by nilsishome**
**UPDATED: I have implemented new code - as well as removed deprecated code - in HTML, SCSS and JavaScript; for screen readers and more accessibility overall!**

**The functionality for filter by rating is complete**
I have tested this functionality in Firefox and Safari, and it works as expected.

- Two functions were created in a new JavaScript folder: filterByRating() and resetForm().
- resetForm() is probably not needed in most webbrowsers, but is necessary for e.g Firefox.
- index.js was slightly changed, as I implemented the two new functions, as well as added a Global Attribute to the rooms in generateRoom(), called **rating**. It takes the rating value from API and implements it in the rooms DOM elements.
- When the first star rating is higher than the second one; no challenges show up.

Screenshot 2024-11-22 at 17 37 12

Screenshot 2024-11-22 at 17 37 55

Screenshot 2024-11-22 at 17 37 41

### CODE REVIEW

**Comment by nilsishome** [comment]
Forgot to mention: The first star in the first star rating has a value of 0, while the first star in the second star rating has a value of 1.
That is because we have rooms that are greater than 0 but have a lower value than 1.

**UPDATED:** _This is no longer the case, because of the functionality of removing stars; if pressed twice._

**Comment by viktornoskire** [comment]
Looks very good and works as intended! I don't know if it's possible or necessary but maybe when you have checked a star rating on filter_first_rate, you can't choose a value lower on the second rating. But as I said it's probably not even necessary so I think it's ready to be merged into main.

**Comment by Kalu32k** [comment]
Wow amazing work, good job!

**Comment by nilsishome** [comment]
Thank you Viktor and Calle! Really appreciate your feedback!

**Comment by Hungryhippoafk** [comment]
Excellent work! way to go!

**Comment by viktornoskire** [comment]
Very good implementation. Works very well. It's ready to be merged.

**Comment by Nishune** [comment]
Looks good! I also think we can merge this with the project. Also i just realised we might need to connect all filters so they "sync" with eachother aswell? But we can talk about this on our meeting =). Good job nils!

**Comment by nilsishome** [comment]
Thank you everyone! I'm happy that you are feeling content with the rating implementation! :)

**Pull request merged**
