### PR TITLE
Add Phone Input Field and Validation for Optional Submission

### PR DESCRIPTION
**Pull request by Hungryhippoafk**
A phone number input field to the form and implements a conditional check to validate whether the phone number is provided. The phone number is optional and will not block form submission if left blank. The changes ensure a better user experience while maintaining form flexibility.

phone input field :

- Added a new phone number input field to the form with and label.
- The input field is clearly marked as optional to inform users that it is not required.

check for phone number:
- added an if statement in the form submission logic to check if the phone number is provided.
- if provided it will log and process the value.
- if the number is not provided, it will skip the validation and proceed with the form submission.

Screenshot 2024-12-04 220348
Screenshot 2024-12-04 220413
Screenshot 2024-12-04 220429

### CODE REVIEW

**Comment by viktornoskire** [comment]
Very good work! 

To add a little more functionality and a ”safe switch” could be to add a condition that the phone number entered cannot be shoter than 5 numbers or longer than 10 according to Swedish numbers. That will ensure the user has entered a valid phone number and not just a single digit. 

That would be on row 162 in the if statement. You could add ”&& phoneCheck >= 5 && phoneCheck <= 10”, I think. To extend the functionality even more, it is possible to add another if statement if the user has not entered a phone number, then the message you have is displayed. But if the user enters an invalid phone number the get a message that it’s not valid.

**Comment by Hungryhippoafk** [comment]
@viktornoskire did not think of that! Will go back and add it to the code
thanks for the excellent feedback!

**Comment by nilsishome** [comment]
Great job, Jimmy! The only implementation left, could be the functionality that Viktor suggested. Then it should not be mistaken for anything else than a Swedish phone number!

**Comment by Hungryhippoafk** [comment]
@nilsishome thank you! i agree, will add and then merge and do a test run of the code.

**Pull request closed without merging**
