### PR TITLE
Structure project

### PR DESCRIPTION
**Pull request by Nishune**
### The final cleanup in the project made by Nils, Viktor, Rikard and Calle.

This was the last group liveshare coding where we made some final touches on the proejct.

In the list below we briefly go through the changes:

- Removed unnecessery javascript files, and added their functionality in navigation.js.
-  Removed javascript SRC from HTML files, now only main.js gets executed there.
- Changed name on index.js to main.js.
- We used type module and exports to run all from main.js.
- Reworked some button javascripts to work with the new structure.

### CODE REVIEW

**Comment by nilsishome** [comment]
Good job to everyone!

**Comment by Nishune** [comment]
Good job, see you on monday!

**Comment by Kalu32k** [comment]
Nothing is broken good job, you may stay in this group for now.

**Comment by viktornoskire** [comment]
Very good structure. Great work! @Nishune @nilsishome @HungryHippo93 @Kalu32k and me of course!

**Pull request merged**
