### PR TITLE
Button hover

### PR DESCRIPTION
**Pull request by Nishune**
### Pull-request for adding hover-effects on buttons and links on the website.

I have added hover-effect on all links and buttons on the website, the list below will go through the changes. I tried to make the hover-effects subtle but still noticable.

### List of changes:

- Updated all mixins for the buttons to now have an hover-effect.
- Used the colors we discussed on Trello where the buttons get darkened, except for the already dark button which gets a abit brighter.
- Fixed a bug in challenges.scss which had incorrect nesting and caused all our h2 elements to get targeted by that specific styling.
- Added hover-effect on the logo-title aswell since it navigates to the homepage.
- Added a few more color-variables in lib.scss which is used for the hover-effects.

### Image preview of button-hover:

Easiest to see this hover-effect is to check in on the branch. Hard to see a difference here! But there sure is a hover-effect. =)

image
image
image
image

### CODE REVIEW

**Comment by nilsishome** [comment]
I think the new implementation of this functionality works great. Though I wonder if the booking modals two buttons should have the same hover effect as well. Or maybe we can do that later, if they were left out intentionally. :)

**Comment by Nishune** [comment]
> I think the new implementation of this functionality works great. Though I wonder if the booking modals two buttons should have the same hover effect as well. Or maybe we can do that later, if they were left out intentionally. :)

Thats is true, i totally forgot about those! I will fix that before we merge this!

**Comment by Nishune** [comment]
> I think the new implementation of this functionality works great. Though I wonder if the booking modals two buttons should have the same hover effect as well. Or maybe we can do that later, if they were left out intentionally. :)

I have now added the same hover effects as used on the rest of the site!

**Comment by nilsishome** [comment]
> > I think the new implementation of this functionality works great. Though I wonder if the booking modals two buttons should have the same hover effect as well. Or maybe we can do that later, if they were left out intentionally. :)
> 
> I have now added the same hover effects as used on the rest of the site!

Well done! Now I have nothing to complain about! ;)

**Pull request merged**
