### PR TITLE
Added the function to post to api, and reworked the html,

### PR DESCRIPTION
**Pull request by Hungryhippoafk**
New Javascript file containing the POST to api functionality,
tested and works.
Reworked the html code - changed to "label for" and added to time label an selection option displaying two times (ex : 13:30-14:30).
added an error if entering non email type,  @gmail.com - works.
Screenshot 2024-11-19 224217
Screenshot 2024-11-19 223957
Screenshot 2024-11-19 224007
Screenshot 2024-11-19 224241

Please let me know if something needs to improve or remove,

This is still a work in progress.
Overview the code if you see something looking fishy.

Thanks!

### CODE REVIEW

**Comment by nilsishome** [comment]
Looks like a really nice start! 
The time of day is hardcoded in HTML as of now, and I'm wondering if it should be taking values directly from the API instead? Or if that is even possible? 
And I'm not sure what the 'data' variable is currently doing. I think it looks good otherwise!

**Comment by Nishune** [comment]
I agree with Nils, the "hardcoded" html values could probably be removed and be replaced with the time values from the API? But we can look together at our meeting aswell=) good job overall, looks like we might have something here !

**Comment by Hungryhippoafk** [comment]
Totally agree with you all, a meeting and together work out the time and date connection with api!
I fixed the js api POST on this, and i think i got it to work, but adding a picture of a test run in live server.
Thanks for the excellent feedback!.
image

**Comment by Hungryhippoafk** [comment]
Good day.
Kalu32k and hungryhippoafk has created a listener for the button between modal 1 - modal 2. 
The info from modal 1 api (date,time) now being sent to modal 2 .
Change the time options now to only display available times from api depending on date chosen.
Check out the code and how it runs during next meeting. Styling fixes will apply later.
Clicking outside to close still applies for modal2 - question if we still want this to remain when project is done.

Thanks !

**Comment by Kalu32k** [comment]
So great that we got the times working, now we just need to add what challenge is chosen and how many participants for the drop down menu.

**Pull request merged**
