### PR TITLE
Connect modal

### PR DESCRIPTION
**Pull request by Kalu32k**
Updated the branch and recreated the javascript with its own html elements

### CODE REVIEW

**Comment by Nishune** [comment]
Nice work, i think we can merge this so we all can start working together to make the booking module work correctly.

The module is not able to close right now without adding a date, so this also needs to be fixed, but we can fix this when we work together !

**Comment by nilsishome** [comment]
I agree with Rikard! It looks good so far otherwise!

**Comment by Kalu32k** [comment]
Now the first modal is hidden by default.

**Comment by Nishune** [comment]
> Now the first modal is hidden by default.

Good job!

**Pull request merged**
