### PR TITLE
Room styling

### PR DESCRIPTION
**Pull request by Nishune**
### What has been added, an overview:

- Added SCSS for the challenges that are displayed on challenges.html
- Fixed some javascript, since i had missed that the stars are now supposed to be ontop of the IMG.
- Added Roboto font from google on the challenges.html file.

### Discussion:

I think this styling is kinda working for now, but it probably needs to be better. But maybe it works for now while we work on the project!

Image of the styling:

image

### CODE REVIEW

**Comment by Kalu32k** [comment]
Nice work!
It looks good, maybe we can add the fa-star and have the unmarked star be faded?
https://fontawesome.com/v4/icon/star 
image

**Comment by Hungryhippoafk** [comment]
Looks really good! great work with the styling, maybe later you could add the "onsite" and "online" icons to be displayed on the images that are in those categories.

**Comment by nilsishome** [comment]
Looks very good! I like the styling of the rating-stars as they are, but I'm _not_ against Calles suggestion. Is this applied to the index.html **page** as well?

**Comment by Nishune** [comment]
> Nice work! It looks good, maybe we can add the fa-star and have the unmarked star be faded? https://fontawesome.com/v4/icon/star image

Yes, i think the stars might need to change overall, since they dont display "Half-stars" at the moment!

**Comment by Nishune** [comment]
> Looks really good! great work with the styling, maybe later you could add the "onsite" and "online" icons to be displayed on the images that are in those categories.

Yes that is true i actually missed that aswell! Ill take a look at that!

**Comment by Nishune** [comment]
> Looks very good! I like the styling of the rating-stars as they are, but I'm _not_ against Calles suggestion. Is this applied to the index.html file as well?

This is only for the challenges.html for the moment, i think ill do a separate styling for the "top-3 rooms" since these also have a mobile-version for their styling. But im not sure yet!

**Comment by Nishune** [comment]
### Update on previous pull request since it wasnt ready for merge!

### In the list below i will show what has been done:

- Fixed some SCSS by adding rounded corners to the challenges which i had missed before.
- Added more Javascript in the generateRoom function, so it now adds an icon depending on what room type it is. (As requested by Calle)
- Imported icons from fontawesome library, i could not find the same icon as on whimsical for the computer. These are not in the <head>-section on challenges.html.
- Added SCSS for the icons to give them the correct position on the image, set color to dark gray for now, guess we can discuss later what color we should use here?


### Preview image of how it looks right now:

image

**Comment by Hungryhippoafk** [comment]
Looks really good! the icons on the cards looks right and are generated on the right card.
fantastic work!

**Comment by nilsishome** [comment]
I agree with Jimmy on this topic! Nicely done adding the icons and making a clean card design, overall.

**Comment by Nishune** [comment]
I still have not fixed the stars in this PR, i think i will make a new branch where i fix the styling for the top-3 rooms and also add some javascript to grab fontawesome icons for the stars, and fix so we can show "half-star rating" aswell.

**Pull request merged**
