### PR TITLE
Loading indicator before challenges cards on challenges.html shows.

### PR DESCRIPTION
**Pull request by Hungryhippoafk**
Added an loading indicator to be shown when user enters onsite or online in navigation.
An circle with dark blue and red appears in a spinning, added a timer to be shown for 1 sec before the cards appear.
- added an if statement to check if the pathname ends with /challenges.html.
- and if it does and loading indicator appears.
Created a separeted js file for the loading indicator, used export and import to be able to use the code in main.js file.

Test:
See that the loading indicator is visible.
see that the loading indicator disappears after 1sec.
see that the loading indicator only works on onsite and online in nav.
see that the loading indicator is not visible on main page or in modules, filters.

Thanks!

Screenshot 2024-12-10 105117

### CODE REVIEW

**Comment by viktornoskire** [comment]
Great work and very cool loading indicator. I think it's a very nice animation. One thing I would change to make the user experience even better would be to put the loading indicator div into the challenges__container div and use margin-left, margin-right to be auto. That will make sure the indicator is in the center of the div. In my opinion it makes more sense to put it inside the div instead of on a fixed position the screen.

**Comment by Hungryhippoafk** [comment]
Great feedback! and totally makes sense! will do so!

**Comment by viktornoskire** [comment]
I made one mistake when I said the challenges__container, I meant the challenges div. The one which class name is just challenges. @Hungryhippoafk

**Comment by Hungryhippoafk** [comment]
Changed what @viktornoskire referred to, and made it user friendly.
added 300 in setTimeout to decrease the hack before challenges loads in.

Check it out

**Comment by viktornoskire** [comment]
Very good! You showed me on Discord and it looks very good. It's ready to merge with main. I can't say it enough, but the animation is super cool.

**Pull request merged**
