### PR TITLE
Step 1 booking modal

### PR DESCRIPTION
**Pull request by Kalu32k**
image
Created a template for the booking modal step 1 based on the design so we can start working on it.

Contains small amount of HTML and CSS, no Javascript yet.

### CODE REVIEW

**Comment by nilsishome** [comment]
Looks like a clean start! Nothing to add from my part so far. Well done 👍

**Comment by Nishune** [comment]
Good job, i think the modal looks good to have as a "graphic layout" while we work on the project. But you should probably add some functionality so it can be closed, maybe a X-button to be able to close the modal? On whimsical is there no close button tho, maybe add functionality so the modal closes when you press outside of the "box"? I would say a X-button should always be present for user experience but not sure how far we are allowed to choose freely here =)

**Comment by Hungryhippoafk** [comment]
Looks really good! like Nishune wrote, maybe add an functionality to be able to close the box if pressed outside :)
Great work!

**Comment by Kalu32k** [comment]
image
Updated with a functional close button and a input that selects date by calendar.
image
Dates check available slot times data and output in the console when search times button is pressed for now so we can use on second modal.
image
Give console error if no date is selected, might change it into an alert for the user.

**Comment by Kalu32k** [comment]
image
Changed width and height

**Comment by Nishune** [comment]
Nice work calle, think we should be able to merge the modals now? and keep working on their functionality?

**Comment by viktornoskire** [comment]
I agree with Nishune. It looks very clean. Resolve some conflicts and then it's ready to be merged.

**Pull request merged**
